import type { Metadata } from 'next'
import { Inter, Cairo, Fraunces, Open_Sans } from 'next/font/google'
import './globals.css'

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})
const cairo = Cairo({ 
  subsets: ['latin'],
  variable: '--font-cairo',
})
const fraunces = Fraunces({ 
  subsets: ['latin'],
  variable: '--font-fraunces',
})

export const metadata: Metadata = {
  title: `I can't stop`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${openSans.className}  ${cairo.variable} ${fraunces.variable}`}>{children}</body>
    </html>
  )
}
