import type { Metadata } from 'next'
import { Inter, Cairo } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const cairo = Cairo({ 
  subsets: ['latin'],
  variable: '--font-cairo',
})

export const metadata: Metadata = {
  title: `I can't stop`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${cairo.variable}`}>{children}</body>
    </html>
  )
}
